### ISSUE TITLE
TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by gerroon** [Siot/PaWebControl#50]
Debian Buster X64

```
a user connected
(node:18494) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of null
    at new SinkInput (/opt/PaWebControl/src/backend/sinkInput.ts:40:13)
    at filteredOutput.forEach (/opt/PaWebControl/src/backend/pactl.ts:88:25)
    at Array.forEach (<anonymous>)
    at Pactl.<anonymous> (/opt/PaWebControl/src/backend/pactl.ts:86:20)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/PaWebControl/src/backend/pactl.ts:4:58)
(node:18494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or
 by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js 
process with a non-zero exit code.
(node:18494) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of null
    at new SinkInput (/opt/PaWebControl/src/backend/sinkInput.ts:40:13)
    at filteredOutput.forEach (/opt/PaWebControl/src/backend/pactl.ts:88:25)
    at Array.forEach (<anonymous>)
    at Pactl.<anonymous> (/opt/PaWebControl/src/backend/pactl.ts:86:20)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/PaWebControl/src/backend/pactl.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or
 by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18494) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of null
    at new SinkInput (/opt/PaWebControl/src/backend/sinkInput.ts:40:13)
    at filteredOutput.forEach (/opt/PaWebControl/src/backend/pactl.ts:88:25)
    at Array.forEach (<anonymous>)
    at Pactl.<anonymous> (/opt/PaWebControl/src/backend/pactl.ts:86:20)
```

**Comment by Siot** [comment]
what's the output if you run in console:

pactl list

**Comment by gerroon** [comment]
I get a long list of output about 1287 lines

**Comment by gerroon** [comment]
This error seems to happen when there is a playback activity with sound output and I cant access to the webpage , all I get is a white page. If I stop the playback, then error does not happen and I can see the control page again.

**Comment by Siot** [comment]
The parse script is weak. Extracts information from a big text without an easy parseable formal.
Also try to always get the command output in English (with LANG=C env). But I can't guarantee a correct parsing in every version of system, systemd, pactl...

I think the data for this error cames from de command:
`LANG=C pactl list sink-inputs`

Could you attach the output of this command please?

Thank you

**Comment by gerroon** [comment]
https://paste.debian.net/hidden/6ab8347f/

**Comment by Devorlon** [comment]
Ditto on the issue. White screen and errors in the terminal. I've attached the script running and the error loop:

https://pastebin.com/6FrteVbA

And here's the output of  `LANG=C pactl list sink-inputs`:

https://pastebin.com/Nn6uPsbM

**Comment by Siot** [comment]
Thank you. The output format of pactl list it's not parse friendly and I don't have too much time for a program I'm not currently using.

Contributions are welcome.
